repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check
        language: system
        types: [python]
        args: [--fix]
        exclude: __pycache__|\.pyc$
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
        exclude: __pycache__|\.pyc$
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--config-file=pyproject.toml]
        exclude: __pycache__|\.pyc$
 